---
- name: Test setup
  hosts: all
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: true
      changed_when: false
      when: ansible_facts["os_family"] == "Debian"

- name: Converge
  hosts: all
  become: true
  vars:
    sixfour_ports: [30080]
  roles:
    - role: blackieops.sixfour
